addSbtPlugin("com.codecommit"    % "sbt-github-actions"  % "0.10.1")
addSbtPlugin("com.codecommit"    % "sbt-github-packages" % "0.5.2")

addSbtPlugin("com.eed3si9n"      % "sbt-unidoc"          % "0.4.3")
addSbtPlugin("com.eed3si9n"      % "sbt-assembly"        % "0.15.0")
addSbtPlugin("com.eed3si9n"      % "sbt-buildinfo"       % "0.9.0")
addSbtPlugin("com.typesafe.sbt"  % "sbt-site"            % "1.4.1")
addSbtPlugin("com.typesafe.sbt"  % "sbt-native-packager" % "1.8.0")
addSbtPlugin("com.typesafe.sbt"  % "sbt-git"             % "1.0.0")
addSbtPlugin("org.lyranthe.sbt"  % "partial-unification" % "1.1.2")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"       % "1.6.1")
addSbtPlugin("com.codacy"        % "sbt-codacy-coverage" % "3.0.3")